name: Build ai-chat

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4

      - name: Install Android NDK
        run: sdkmanager "ndk;29.0.13113456"

      - name: Build ai-chat
        working-directory: .
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Upload ai-chat library
        uses: actions/upload-artifact@v4
        with:
          name: ai-chat-libs
          path: llama.cpp/examples/llama.android/lib/build/intermediates/stripped_native_libs/release/out/lib/arm64-v8a/libai-chat.so
